services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: My027
      POSTGRES_DB: quantum_bluff
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-quantum
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
