version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: My027
      POSTGRES_DB: quantum_bluff
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
