server {
    listen 80;
    server_name _;

    # 1. Reverse proxy pour l'API du Backend
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Reverse proxy pour les WebSockets (Socket.IO)
    location /socket.io/ {
        proxy_pass http://backend:3000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

<<<<<<< HEAD
    # 3. Reverse proxy pour le Frontend
    location / {
        proxy_pass http://frontend:80/; # Si le frontend crashe, remplace 80 par 5173
        proxy_set_header Host $host;
    }
}
=======
    location /vmProjetIntegrateurgrp10-0/socket.io/ {
        proxy_pass http://backend:3000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # REDIRECTION HTTPS (A décommenter après l'étape Certbot)
    # location / {
    #     return 301 https://$host$request_uri;
    # }
}

# BLOC HTTPS (A décommenter APRES avoir généré le certificat SSL avec Certbot)
# server {
#     listen 443 ssl;
#     server_name quantum-bluff.fr www.quantum-bluff.fr;
#
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_certificate /etc/letsencrypt/live/quantum-bluff.fr/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/quantum-bluff.fr/privkey.pem;
#
#     # (Copier ici les locations /, /api/ et /socket.io/ du bloc ci-dessus)
# }
>>>>>>> 73e8f0045ffb50b9bf5ee005ea5bd028bbe00ab1
